# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
        ('course_app', '0002_course_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user_id',
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(to='login_reg_app.User'),
        ),
    ]
